export interface IGiftCard {
  id: number;
  cardName: string;
  value: number;
  expirationDate: string;
  isActive: boolean;
  recipientEmail: string;
}

export const giftCardData: IGiftCard[] = [
  {
    id: 1,
    cardName: "Amazon Gift Card",
    value: 50,
    expirationDate: "2025-12-31",
    isActive: true,
    recipientEmail: "john.doe@example.com",
  },
  {
    id: 2,
    cardName: "Google Play Gift Card",
    value: 25,
    expirationDate: "2025-06-30",
    isActive: false,
    recipientEmail: "jane.smith@example.com",
  },
  {
    id: 3,
    cardName: "Apple Gift Card",
    value: 100,
    expirationDate: "2026-01-01",
    isActive: true,
    recipientEmail: "michael.brown@example.com",
  },
  {
    id: 4,
    cardName: "Netflix Gift Card",
    value: 75,
    expirationDate: "2024-11-15",
    isActive: false,
    recipientEmail: "susan.jones@example.com",
  },
  {
    id: 5,
    cardName: "Spotify Gift Card",
    value: 30,
    expirationDate: "2025-09-20",
    isActive: true,
    recipientEmail: "chris.white@example.com",
  },
  {
    id: 6,
    cardName: "Walmart Gift Card",
    value: 60,
    expirationDate: "2026-03-10",
    isActive: true,
    recipientEmail: "anna.bell@example.com",
  },
  {
    id: 7,
    cardName: "Steam Wallet Card",
    value: 40,
    expirationDate: "2025-07-07",
    isActive: false,
    recipientEmail: "david.king@example.com",
  },
  {
    id: 8,
    cardName: "Uber Gift Card",
    value: 20,
    expirationDate: "2025-04-22",
    isActive: true,
    recipientEmail: "emma.wilson@example.com",
  },
  {
    id: 9,
    cardName: "eBay Gift Card",
    value: 90,
    expirationDate: "2026-12-25",
    isActive: true,
    recipientEmail: "will.james@example.com",
  },
  {
    id: 10,
    cardName: "Target Gift Card",
    value: 45,
    expirationDate: "2024-11-30",
    isActive: false,
    recipientEmail: "olivia.martin@example.com",
  },
  {
    id: 11,
    cardName: "Sephora Gift Card",
    value: 70,
    expirationDate: "2025-08-15",
    isActive: true,
    recipientEmail: "sophia.brown@example.com",
  },
  {
    id: 12,
    cardName: "Adidas Gift Card",
    value: 55,
    expirationDate: "2025-05-01",
    isActive: false,
    recipientEmail: "liam.davis@example.com",
  },
  {
    id: 13,
    cardName: "Nike Gift Card",
    value: 35,
    expirationDate: "2026-09-10",
    isActive: true,
    recipientEmail: "elijah.moore@example.com",
  },
  {
    id: 14,
    cardName: "Best Buy Gift Card",
    value: 80,
    expirationDate: "2026-01-20",
    isActive: true,
    recipientEmail: "noah.taylor@example.com",
  },
  {
    id: 15,
    cardName: "Disney Gift Card",
    value: 65,
    expirationDate: "2024-10-31",
    isActive: false,
    recipientEmail: "mia.johnson@example.com",
  },
  {
    id: 16,
    cardName: "Uber Eats Gift Card",
    value: 25,
    expirationDate: "2025-03-15",
    isActive: true,
    recipientEmail: "james.lee@example.com",
  },
  {
    id: 17,
    cardName: "H&M Gift Card",
    value: 50,
    expirationDate: "2026-05-25",
    isActive: true,
    recipientEmail: "lucas.thomas@example.com",
  },
  {
    id: 18,
    cardName: "Zara Gift Card",
    value: 45,
    expirationDate: "2025-12-01",
    isActive: false,
    recipientEmail: "ella.jackson@example.com",
  },
  {
    id: 19,
    cardName: "Starbucks Gift Card",
    value: 15,
    expirationDate: "2024-08-20",
    isActive: true,
    recipientEmail: "grace.white@example.com",
  },
  {
    id: 20,
    cardName: "iTunes Gift Card",
    value: 30,
    expirationDate: "2026-02-14",
    isActive: true,
    recipientEmail: "harper.harris@example.com",
  },
];
